language: python
dist: focal
python:
  - "3.10"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:

  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
  - python3 -m pip install telebot pymongo aiohttp psutil motor pytz asyncssh

script:

  - chmod +x * && lscpu && python3 daku.py
  
                               